databases:
  - name: bookmyevent-db
    plan: free
    databaseName: bookmyevent
    user: bookmyevent

services:
  - type: web
    name: bookmyevent-api-abhijit
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:backend
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://book-my-event-vite.vercel.app
      - key: CLIENT_URLS
        value: https://book-my-event-vite.vercel.app
      - key: SYNC_DB
        value: true
      - key: SEED_DB
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: bookmyevent-db
          property: connectionString
      - key: DB_DIALECT
        value: postgres
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: 8h
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GEOAPIFY_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: BANK_ACCOUNT_ENCRYPTION_KEY
        generateValue: true
      - key: ADMIN_COMMISSION_PERCENT
        value: 10
      - key: PLATFORM_FEE
        value: 500
      - key: ADVANCE_AMOUNT
        value: 1000
      - key: PAYMENT_DUE_HOURS
        value: 48
